package org.wojtekz.akademik.namedbean;

import java.util.ArrayList;
import java.util.List;

import javax.enterprise.context.SessionScoped;
import javax.inject.Named;

import org.apache.log4j.Logger;
import org.springframework.beans.factory.annotation.Autowired;
import org.wojtekz.akademik.entity.Student;
import org.wojtekz.akademik.repos.StudentRepository;

import java.io.Serializable;

/**
 * Obs³uga studentów od strony aplikacji JSF.
 * 
 * @author wojtek
 *
 */
public class StudentBean implements Serializable {
	/**
	 * Generated by Eclipse.
	 */
	private static final long serialVersionUID = 297092190215801549L;

	private static Logger logg = Logger.getLogger(StudentBean.class.getName());
	
	@Autowired
	StudentRepository studentRep;
	
	/**
	 * Pobiera listê studentów z bazy i przekszta³ca na Stringi czytelne dla strony web.
	 * 
	 * @return lista studentów
	 */
	public List<String> pobierzStudentow() {
		logg.debug("----->>> pobierzStudentow start");
		List<String> studenci = new ArrayList<>();
		List<Student> listaStudentow = studentRep.findAll();
		
		for (Student ss : listaStudentow) {
			studenci.add(ss.toString());
		}
		
		logg.debug("----->>>  mamy studentów dla stronki");
		return studenci;
	}
	

}
